from .add_car_owner import AddCarOwnerRepositoryInterface
from .add_car import AddCarRepositoryInterface
from .list_cars import ListCarsRepositoryInterface
from .list_car_owners import ListCarOwnersRepositoryInterface
